// <auto-generated />
using System;
using GitlabInfo.Code.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GitlabInfo.Migrations
{
    [DbContext(typeof(GitLabInfoDbContext))]
    [Migration("20190305152721_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GitlabInfo.Models.EFModels.GroupModel", b =>
                {
                    b.Property<int>("Id");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GitlabInfo.Models.EFModels.ProjectModel", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("GroupModelId");

                    b.HasKey("Id");

                    b.HasIndex("GroupModelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GitlabInfo.Models.EFModels.UserGroupModel", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GroupId");

                    b.Property<int>("Role");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroupModel");
                });

            modelBuilder.Entity("GitlabInfo.Models.EFModels.UserModel", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("FirstJoined");

                    b.Property<DateTime>("LastJoined");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GitlabInfo.Models.EFModels.ProjectModel", b =>
                {
                    b.HasOne("GitlabInfo.Models.EFModels.GroupModel")
                        .WithMany("Projects")
                        .HasForeignKey("GroupModelId");
                });

            modelBuilder.Entity("GitlabInfo.Models.EFModels.UserGroupModel", b =>
                {
                    b.HasOne("GitlabInfo.Models.EFModels.GroupModel", "Group")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GitlabInfo.Models.EFModels.UserModel", "User")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
